# Generated by Django 3.0.4 on 2020-03-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autenticavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
    ]
